### PR TITLE
Created a high-level basic Python w/ Selenium example

### PR DESCRIPTION
**Pull request by Ayiden**
Created a very basic Python w/ Selenium test. Will access a URL link, enter text, click a button, pull text, and validate that text displays using basic asserts and try/except exception handling

### CODE REVIEW

**Comment by Ayiden** [comment]
I want this to be a super raw example to start. Something that shows the very basics of Python as an example before building out a more sustainable model

**Review by eschlange — APPROVED** [review]

**Comment by eschlange** [comment]
Looks good, approved.  I only have two notes:

1. Updating the example filename to be more descriptive (ex. example_webdriver_initialization.py) would help people browsing through the files through GitHub. 
2. Wrapping the example code in a function helps affirm standard Python functional programming practices, for example:
```
def main():
    # Add existing example logic here.

if __name__ == "__main__":
    main()
```
(https://learnpython.com/blog/write-main-function-python/)
I can make that update on the next PR though.

**Comment by Ayiden** [comment]
> Looks good, approved. I only have two notes:
> 
> 1. Updating the example filename to be more descriptive (ex. example_webdriver_initialization.py) would help people browsing through the files through GitHub.
> 2. Wrapping the example code in a function helps affirm standard Python functional programming practices, for example:
> 
> ```
> def main():
>     # Add existing example logic here.
> 
> if __name__ == "__main__":
>     main()
> ```
> 
> (https://learnpython.com/blog/write-main-function-python/) I can make that update on the next PR though.

That's a good call. I'll make those changes and can wrap it. It's a great callout to still utilize those basic Python standards even in a low level example. I'll update the PR with the change and ping you directly in a comment as well :)

**Comment by Ayiden** [comment]
@eschlange Just included those changes. Let me know if that looks good. Thanks for the notes!

**Pull request merged**
